# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('point_0', models.BooleanField()),
                ('point_1', models.BooleanField()),
                ('point_2', models.BooleanField()),
                ('point_3', models.BooleanField()),
                ('point_4', models.BooleanField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
