# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='point_0',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='point_1',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='point_2',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='point_3',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='point_4',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='point',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
