# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0003_dailymenu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='all',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='restaurant',
            field=models.ForeignKey(default='301동', on_delete=django.db.models.deletion.CASCADE, to='snuseggi.Restaurant'),
        ),
    ]
