# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0005_auto_20160602_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='all',
        ),
    ]
