# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0006_remove_restaurant_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('L', 'Lunch'), ('D', 'Dinner')], default='L', max_length=1)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snuseggi.Restaurant')),
            ],
        ),
        migrations.AlterField(
            model_name='assessment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
