# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0006_auto_20160601_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.AddField(
            model_name='assessment',
            name='classification',
            field=models.CharField(choices=[('L', 'Lunch'), ('D', 'Dinner')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='restuarant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snuseggi.Restaurant'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='menus',
            field=models.ManyToManyField(to='snuseggi.Menu'),
        ),
    ]
