# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0007_auto_20160602_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='menu',
        ),
        migrations.AddField(
            model_name='assessment',
            name='dailyMenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='snuseggi.DailyMenu'),
        ),
    ]
