# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0010_auto_20160603_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='classification',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='classification',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='select',
            name='classification',
            field=models.CharField(blank=True, choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=6, null=True),
        ),
    ]
