# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0011_auto_20160605_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailymenu',
            name='name',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='classification',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=6),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='classification',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=6),
        ),
        migrations.AlterField(
            model_name='select',
            name='classification',
            field=models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=6),
        ),
    ]
