# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0012_auto_20160605_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='dailyMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snuseggi.DailyMenu'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='point_price',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='point_service',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='point_taste',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='restaurant',
            field=models.ForeignKey(default='301동', on_delete=django.db.models.deletion.CASCADE, to='snuseggi.Restaurant'),
        ),
        migrations.AlterField(
            model_name='select',
            name='restaurant',
            field=models.ForeignKey(default='301동', on_delete=django.db.models.deletion.CASCADE, to='snuseggi.Restaurant'),
        ),
    ]
