# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0014_restaurant_point_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='point_average',
            field=models.FloatField(default=0),
        ),
    ]
