# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snuseggi', '0015_auto_20160613_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='classification',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=6),
        ),
        migrations.AlterField(
            model_name='dailymenu',
            name='classification',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=6),
        ),
        migrations.AlterField(
            model_name='select',
            name='classification',
            field=models.CharField(choices=[('BreakFast', 'BreakFast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Lunch', max_length=6),
        ),
    ]
